name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        mkdir -p storage/framework/{views,cache}
        sudo chown www-data:www-data -R storage
        sudo chmod o+rwx -R storage
        ls -la storage/framework
    - name: Generate key
      run: php artisan key:generat
    #- name: Directory Permissions
    #  run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        php artisan cache:clear
        php artisan config:clear
        
    - name: Deploy to Stage Server
      if: github.ref == 'refs/heads/master'
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          #ARGS: "-rltgoDzvO --delete"
          ARGS: "-rvza"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.STAGE_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.STAGE_REMOTE_USER }}
          TARGET: ${{ secrets.STAGE_REMOTE_TARGET }}

